name: build and push images

on:
  push:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        postgres: [10, 11, 12, 13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,event=branch,value=${{ matrix.postgres }},enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,prefix=${{ matrix.postgres }}-
            type=ref,prefix=${{ matrix.postgres }}-,suffix=,event=branch

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
