name: build and push images

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - { postgres: 12, alpine: '3.12' }
          - { postgres: 13, alpine: '3.14' }
          - { postgres: 14, alpine: '3.16' }
          - { postgres: 15, alpine: '3.17' }
          - { postgres: 16, alpine: '3.19' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,event=branch,value=${{ matrix.postgres }}
            type=sha,prefix=${{ matrix.postgres }}-
            type=ref,prefix=${{ matrix.postgres }}-,suffix=,event=branch

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
